# Generated by Django 6.0.6 on 2026-07-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_must_change_password_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(default='RWF', max_length=10),
        ),
    ]
